### ISSUE TITLE
CSV import timestamp and object

### ISSUE THREAD

**Issue by alon-mixpanel** [ak--47/toMixpanel#3]
When using the CSV import and putting epoch time will result in an error importing.
Also would love to see the option to see an object that is in the csv

**Comment by ak--47** [comment]
@alon-mixpanel

will address the time bug. thanks for raising.

probably not the "nested objects in CSV" feature request. i do not think that is a common data format.

**Comment by ak--47** [comment]
@alon-mixpanel 

https://github.com/ak--47/toMixpanel/commit/52137c7184a27ace1d5be7824291a2872fd0c3b8 addresses epoch time.
