### ISSUE TITLE
Mixpanel to Mixpanel tag 

### ISSUE THREAD

**Issue by alon-mixpanel** [ak--47/toMixpanel#4]
When importing from a different project I'd like to have in the config the ability to add a tag so i can test the data based on a property

**Comment by ak--47** [comment]
@alon-mixpanel 

in the destination, something like

```json
"options": {
  "tag": "my tag" //this value would be on all events + users
}
```

right?

**Comment by alon-mixpanel** [comment]
That’s right. Thanks

**Comment by ak--47** [comment]
@alon-mixpanel this now works for CSV files. the tag is called `import-tag` in the data.

https://github.com/ak--47/toMixpanel/blob/main/examples/configExample-csv.json#L15
